DEBUG: Executing python function do_mypatch
NOTE: runnin mypatch
ERROR: Error executing a python function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:do_mypatch(d)
     0003:
File: '/home/chenqinghui/bbTutorial/meta-tutorial/recipes-tutorial/second/second_1.0.bb', lineno: 8, function: do_mypatch
     0004:def pyfunc(o):
     0005:   printdir (o)
     0006:python do_mypatch () {
     0007:   bb.note ("runnin mypatch")
 *** 0008:   pyfunc(o)
     0009:}
     0010:addtask mypatch before do_build
     0011:
Exception: NameError: name 'o' is not defined

DEBUG: Python function do_mypatch finished
ERROR: Function failed: do_mypatch
