DEBUG: Executing python function do_mypatch
NOTE: runnin mypatch
ERROR: Error executing a python function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:do_mypatch(d)
     0003:
File: '/home/chenqinghui/bbTutorial/meta-tutorial/recipes-tutorial/second/second_1.0.bb', lineno: 6, function: do_mypatch
     0002:PR = "r1"
     0003:inherit mybuild
     0004:python do_mypatch () {
     0005:   bb.note ("runnin mypatch")
 *** 0006:   pyfunc(d)
     0007:}
     0008:addtask mypatch before do_build
     0009:
Exception: NameError: name 'pyfunc' is not defined

DEBUG: Python function do_mypatch finished
ERROR: Function failed: do_mypatch
